spring.application.name=hello-xld-xlr

app.version=@project.version@
app.environment=${APP_ENVIRONMENT:LOCAL}

server.port=8080

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always